---

- name: Check existence of wallabag systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ wallabag_identifier }}.service"
  register: wallabag_service_stat

- when: wallabag_service_stat.stat.exists | bool
  block:
    - name: Ensure wallabag service is stopped
      ansible.builtin.service:
        name: "{{ wallabag_identifier }}"
        state: stopped
        daemon_reload: true
    - name: Ensure wallabag service doesn't exist
      ansible.builtin.file:
        dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ wallabag_identifier }}.service"
        state: absent

    - name: Ensure wallabag base path is files deleted (make sure to delete node data)
      ansible.builtin.file:
        path: "{{ wallabag_base_path }}"
        state: absent
